//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Absent_MG
{
    using System;
    using System.Collections.Generic;
    
    public partial class excute
    {
        public int ex_Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string ex_type { get; set; }
        public string descrp { get; set; }
        public string doc { get; set; }
        public string status { get; set; }
        public Nullable<int> cr_id { get; set; }
        public Nullable<int> inst_id { get; set; }
        public Nullable<int> st_id { get; set; }
        public Nullable<int> sec_id { get; set; }
    
        public virtual course_schedu course_schedu { get; set; }
        public virtual instructor instructor { get; set; }
        public virtual section section { get; set; }
        public virtual student student { get; set; }
    }
}
