//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Absent_MG
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_cr
    {
        public int Id { get; set; }
        public Nullable<int> cr_id { get; set; }
        public Nullable<int> st_id { get; set; }
    
        public virtual course_schedu course_schedu { get; set; }
        public virtual student student { get; set; }
    }
}
